create user api
k-tkm/kintai pull request #4
Opened 2022-05-30 23:10 UTC by k-tkm

2022-06-13 01:09 UTC, kbwo requested changes
動作確認とかはしてないです

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/auth/auth.module.ts
> +        secret: process.env.JWT_SECRET,
ConfigModule使って書けないですか？

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/auth/auth.module.ts
> +        signOptions: { expiresIn: '1d' },
期間も環境変数にしちゃって良い気がする

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/auth/jwt.strategy.ts
> +      secretOrKey: process.env.JWT_SECRET,
ここもできればConfigModuleで

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/auth/jwt.strategy.ts
> +    return { userID: payload.userID };
validationを実装していないのは意図してます？他のPRで実装するてこと？

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/users/Dto/SaveUserDto.ts
> +  @IsNotEmpty({ message: '姓は入力必須です。' })
"入力"という単語はAPIからのレスポンスとしてふさわしくない気がする
英語のinputならまだわかる気がするけど日本語だとちょっと違和感

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
idってNumberStringなんですか？仮にそうなら型はstringでは
やっていることはフォーマットのバリデーションなのにエラーレスポンスが存在していませんなのも、実際は存在検証してないよねって思いますかね
あとクラス名だけど、FindOneって単語よりcontrollerに関係する単語にしたほうが良いと思います
リクエストに対してのバリデーション用クラスってことがコード読まなきゃわからないので

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/users/users.controller.ts
> +export type userDataType = {
型名がlower camelなの風習的に違和感

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/users/users.controller.ts
> +    this.usersService.delete(params.id);
awai明示したほうが良いですね
あと204返すことをコードで明示したほうが良いと思います

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/users/users.service.ts
> +    return savedUser;
early return使ったほうが簡潔です

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/users/users.service.ts
> +    });
ここ関数に切り出したほうが良いですね

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/users/users.service.ts
> +    this.usersRepository.softDelete(userID);
実行待つべきなのでawaitしたほうがいいですね

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/users/users.service.ts
> +  }
await明示したほうが良いと思います

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/auth/auth.service.ts
> +  async login(payload: { userID: number }) {
トークン生成する関数がloginって名前なのは若干違和感があるかなぁ
jwt生成はログインとは言えない気がします

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/auth/auth.service.ts
> +  async login(payload: { userID: number }) {
トークン生成する関数がloginって名前なのは若干違和感があるかなぁ
jwt生成はログインとは言えない気がします

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/auth/auth.service.ts
> +    return { token: token };
`{ token }`

2022-06-13 01:09 UTC, kbwo commented on backend/src/modules/auth/auth.service.ts
> +    return { token: token };
`{ token }`

2022-06-13 01:15 UTC, kbwo commented
やたらレビューの重複コメント作られてたのでそれだけ消しました

2022-06-13 01:58 UTC, k-tkm commented on backend/src/modules/users/users.controller.ts
> +export type userDataType = {
修正しました。
[d50ffe2](https://github.com/k-tkm/kintai/pull/4/commits/d50ffe2157befc7b08b15750fbc7eee4df6e39e9)

2022-06-13 01:59 UTC, k-tkm commented on backend/src/modules/auth/auth.module.ts
> +        secret: process.env.JWT_SECRET,
修正しました。
[119f169](https://github.com/k-tkm/kintai/pull/4/commits/119f1690407af8730c044446d096cf516c6bfd2b)

2022-06-13 01:59 UTC, k-tkm commented on backend/src/modules/auth/jwt.strategy.ts
> +      secretOrKey: process.env.JWT_SECRET,
修正しました。
[119f169](https://github.com/k-tkm/kintai/pull/4/commits/119f1690407af8730c044446d096cf516c6bfd2b)

2022-06-13 02:04 UTC, k-tkm commented on backend/src/modules/auth/auth.module.ts
> +        signOptions: { expiresIn: '1d' },
修正しました。
[58c5ff9](https://github.com/k-tkm/kintai/pull/4/commits/58c5ff900212995f28ad755c04cab7e70d330c68)

2022-06-13 02:05 UTC, k-tkm commented on backend/src/modules/users/Dto/SaveUserDto.ts
> +  @IsNotEmpty({ message: '姓は入力必須です。' })
姓の値が不正です。
とかだとどうすか？

2022-06-13 02:13 UTC, kbwo commented on backend/src/modules/users/Dto/SaveUserDto.ts
> +  @IsNotEmpty({ message: '姓は入力必須です。' })
不正だと汎用的すぎるから普通に必須項目ですとかでいいと思いますよ

2022-06-13 22:51 UTC, k-tkm commented on backend/src/modules/auth/jwt.strategy.ts
> +    return { userID: payload.userID };
validationってのはそのuserIDが本当にデータベースに存在するかを確認するってことですか？

2022-06-13 22:55 UTC, k-tkm commented on backend/src/modules/auth/jwt.strategy.ts
> +    return { userID: payload.userID };
そのユーザーIDが本当に存在するのかを確認する処理を書くべきってことですか？

2022-06-13 22:55 UTC, k-tkm commented on backend/src/modules/users/Dto/SaveUserDto.ts
> +  @IsNotEmpty({ message: '姓は入力必須です。' })
なるほど。ありがとうございます。

2022-06-13 23:11 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
> idってNumberStringなんですか？仮にそうなら型はstringでは

これに関してはNestのドキュメントに書いてあったものをそのまま持ってきたもので、リクエストで来たIDとかはstringになるからこういう書き方をしてるって認識してました。
![スクリーンショット 2022-06-14 8 00 58](https://user-images.githubusercontent.com/73158391/173461389-73a7f1c0-f5dc-47ab-842f-5604fb3e41fb.png)

> フォーマットのバリデーションなのにエラーレスポンスが存在していませんなのも、実際は存在検証してないよねって思いますかね
なるほど。見直します。

> あとクラス名だけど、FindOneって単語よりcontrollerに関係する単語にしたほうが良いと思います
リクエストに対してのバリデーション用クラスってことがコード読まなきゃわからないので

了解です。考え直します。

2022-06-13 23:36 UTC, k-tkm commented on backend/src/modules/users/users.controller.ts
> +    this.usersService.delete(params.id);
修正しました。
[8d02606](https://github.com/k-tkm/kintai/pull/4/commits/8d026061808b6fa2717dda41bdb2a816186270a1)
[eeb56d4](https://github.com/k-tkm/kintai/pull/4/commits/eeb56d4f0e16d91a2971de3a998d39f801dd7e06)

2022-06-13 23:42 UTC, k-tkm commented on backend/src/modules/users/users.service.ts
> +    return savedUser;
修正しました。
[ac6db38](https://github.com/k-tkm/kintai/pull/4/commits/ac6db385a49fc36c73f6c92db44949c654bc9e4e)

2022-06-13 23:44 UTC, k-tkm commented on backend/src/modules/users/users.service.ts
> +    });
このレビューの意図があんまり理解できていないのですが、ここを関数として切り出すってのはどういうことですか？

2022-06-13 23:46 UTC, k-tkm commented on backend/src/modules/users/users.service.ts
> +    this.usersRepository.softDelete(userID);
修正しました。
[30dc372](https://github.com/k-tkm/kintai/pull/4/commits/30dc372ba53f67a7247a0998d64cf3d6522d24b9)

2022-06-13 23:46 UTC, k-tkm commented on backend/src/modules/users/users.service.ts
> +  }
修正しました。
[30dc372](https://github.com/k-tkm/kintai/pull/4/commits/30dc372ba53f67a7247a0998d64cf3d6522d24b9)

2022-06-13 23:48 UTC, k-tkm commented on backend/src/modules/auth/auth.service.ts
> +  async login(payload: { userID: number }) {
issueTokenっていう命名に変更しました。
[23891f4](https://github.com/k-tkm/kintai/pull/4/commits/23891f41553ef9584a934a63c73f688162b6342f)

2022-06-13 23:51 UTC, k-tkm commented on backend/src/modules/auth/auth.service.ts
> +    return { token: token };
修正しました。
[5856cfd](https://github.com/k-tkm/kintai/pull/4/commits/5856cfdc1e12e3ecf5b26be8a52474dcb2b023dc)

2022-06-13 23:54 UTC, k-tkm commented on backend/src/modules/users/users.controller.ts
> +export type userDataType = {
まずSaveUserDtoをそのまま使えそうだったので削除しました。
[703a38d](https://github.com/k-tkm/kintai/pull/4/commits/703a38d938b88f7b32fc5d3b0f8f4bf603eedd92)

2022-06-14 00:00 UTC, k-tkm commented on backend/src/modules/users/Dto/SaveUserDto.ts
> +  @IsNotEmpty({ message: '姓は入力必須です。' })
修正しました。
[3b2dd89](https://github.com/k-tkm/kintai/pull/4/commits/3b2dd8978cff4fabe218e74d227a2a57f9fb0052)

2022-06-14 00:23 UTC, kbwo commented on backend/src/modules/users/users.service.ts
> +    });
```
const existUser = await this.usersRepository.findOne({
      email: email,
    });
```
これを直書きするんじゃなくてemailをキーにしてfindOneする関数を作ってそれを呼ぶ感じにするってことです

2022-06-14 00:23 UTC, kbwo commented on backend/src/modules/auth/jwt.strategy.ts
> +    return { userID: payload.userID };
そうです

2022-06-14 00:23 UTC, kbwo requested changes

2022-06-14 00:23 UTC, kbwo commented on backend/.env.example
> +JWT_EXPIRATION=
JWT_EXPIRATIONのexample書いてください

2022-06-14 00:25 UTC, kbwo commented on backend/src/modules/auth/auth.service.ts
> +  async login(payload: { userID: number }) {
issueって開発では問題とかの方で使われがちだから生成的な意味合いでは使わないほうが良い気がします

2022-06-14 00:48 UTC, k-tkm commented on backend/src/modules/auth/auth.service.ts
> +  async login(payload: { userID: number }) {
じゃあgenTokenですかね？

2022-06-14 00:54 UTC, k-tkm commented on backend/.env.example
> +JWT_EXPIRATION=
かきました。
[1a2d478](https://github.com/k-tkm/kintai/pull/4/commits/1a2d478fee6c0538bd9816753284a61d844c58df)

2022-06-14 00:58 UTC, k-tkm commented on backend/src/modules/users/users.service.ts
> +    });
```
const async  findExistUser = (email: string) => {
  await this.usersRepository.findOne({
      email: email,
    });
}

const existUser = findExistUser(email)
```
多分まだ理解できてないのですが、上のようにするってことですか？

2022-06-14 00:59 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
`リクエストで来たIDとかはstring`
あーなるほど、でも正しい型はstringが正しい気がするけど、調べてみたらnumber型ばっかり出てきた
もしJavaScript上でstringだったらstring型にしといたほうが良いかもしれないです
デコレータがstringからnumberにキャストしてくれるんだったらいらない

2022-06-14 01:00 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
> UserIDDtoとかだと伝わりますか？

getエンドポイントだったらGet〇〇Paramsとか

2022-06-14 01:06 UTC, kbwo reviewed
書き忘れてたけど、返り値の型書いてない部分多いので、基本返り値の型は書いたほうがぼくは良いと思います
書かなくても型推論きくから好みの問題な部分あるけど

2022-06-14 01:06 UTC, kbwo commented on backend/src/modules/users/users.service.ts
> +    });
そうだけどそうじゃないですね
findUserByEmail的なメソッドをクラス自体に作る
そのクラスだけに限定させたいなら必要に応じてprivateメソッドにする

2022-06-14 01:06 UTC, kbwo commented on backend/src/modules/users/users.service.ts
> +    });
そうだけどそうじゃないですね
findUserByEmail的なメソッドをクラス自体に作る
そのクラスだけに限定させたいなら必要に応じてprivateメソッドにする

2022-06-14 01:07 UTC, kbwo commented on backend/src/modules/auth/auth.service.ts
> +  async login(payload: { userID: number }) {
generateをgenて略すの好み分かれそうだけどぼくは良いと思います

2022-06-14 01:13 UTC, monz111 commented on backend/src/modules/auth/auth.service.ts
> +  async login(payload: { userID: number }) {
略したら意味不明だから略さないで欲しい

2022-06-14 01:20 UTC, k-tkm commented on backend/src/modules/auth/jwt.strategy.ts
> +    return { userID: payload.userID };
修正しました。
[70f3e20](https://github.com/k-tkm/kintai/pull/4/commits/70f3e20c70078d6ba09563b0f2f08f6881c8d6d0)

2022-06-14 01:31 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
> もしJavaScript上でstringだったらstring型にしといたほうが良いかもしれないです
デコレータがstringからnumberにキャストしてくれるんだったらいらない

```
__decorate([
    (0, class_validator_1.IsNumberString)({}, { message: 'このユーザーは存在していません。' }),
    __metadata("design:type", Number)
], FindOneParams.prototype, "id", void 0);
exports.FindOneParams = FindOneParams;
```
一応jsに変換されたものを見に行ったらmetadata("design:type", Number)ってなってたんですけど、これはjs上でnumber型になってるってことなんですかね？

> getエンドポイントだったらGet〇〇Paramsとか

了解です。ありがとうございます！

2022-06-14 01:35 UTC, k-tkm commented on backend/src/modules/auth/auth.service.ts
> +  async login(payload: { userID: number }) {
了解です。じゃあgenerateで書きます。

2022-06-14 01:43 UTC, k-tkm commented on backend/src/modules/users/users.service.ts
> +    });
修正しました。
[3fc9d7c](https://github.com/k-tkm/kintai/pull/4/commits/3fc9d7c4e4c7e1dcb2fa05f44d474d36e35ba52c)

これは意図としてはidとかを使わずにemailで取得してくるようなイレギュラーなものは関数として切り出すべきって認識であってますか？

2022-06-14 01:45 UTC, k-tkm commented on backend/src/modules/auth/auth.service.ts
> +  async login(payload: { userID: number }) {
修正しました。
[629863e](https://github.com/k-tkm/kintai/pull/4/commits/629863e3f596a5093419449120123943a49ec581)

2022-06-14 01:46 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
>getエンドポイントだったらGet〇〇Paramsとか
ここの指摘は修正いたしました。

2022-06-14 01:48 UTC, kbwo commented on backend/src/modules/users/users.service.ts
> +    });
idでも

2022-06-14 01:54 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
それ見ただけじゃわからないですが、デコレータなしでtypeof idがstringでありのときnumberならオッケー

2022-06-14 01:58 UTC, k-tkm commented on backend/src/modules/users/users.service.ts
> +    });
なるほど。複数とかで使うことも想定してってことなんすね。
ありがとうございます。

2022-06-14 01:59 UTC, k-tkm commented
> 書き忘れてたけど、返り値の型書いてない部分多いので、基本返り値の型は書いたほうがぼくは良いと思います 書かなくても型推論きくから好みの問題な部分あるけど

このコミットで返り値の型が抜けていた部分には明示的に書くようにしました。
[5e09a0d](https://github.com/k-tkm/kintai/pull/4/commits/5e09a0d1af4a6ef97a5a27276087f28250857416)

2022-06-14 23:11 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
log仕込んでtypeof id で確認したらstiringだったんで、型を修正しました。
[e5637cc](https://github.com/k-tkm/kintai/pull/4/commits/e5637cc985492e2e1e8fe9236c0879f5216d9c61)

2022-06-14 23:24 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
> getエンドポイントだったらGet〇〇Paramsとか
一度このレビューでGetUserParamsDtoに変更したんですけど、DELETEの時とかにも使ってるのでUserParamsDtoとかにしてGETでもDELETEでも使えるようにしたいんですが、命名として大丈夫ですかね？

2022-06-15 00:25 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
良いと思いますよ

2022-06-15 00:36 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
了解です。その命名で修正します。

2022-06-15 00:42 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
修正しました。
[3f22a89](https://github.com/k-tkm/kintai/pull/4/commits/3f22a893b0dddf9cae247e79e276e995fa9bca96)

2022-06-15 00:50 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
> フォーマットのバリデーションなのにエラーレスポンスが存在していませんなのも、実際は存在検証してないよねって思いますかね

またここのレビューですが、文言をどうした方がいいですかね？
このユーザーが検出できませんでした。とかだとどうでしょう？

2022-06-15 00:55 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
このバリデーションはリクエストのフォーマットについてなので検出も関係ないですかね

2022-06-15 00:58 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
なるほど。
パラーメータ値が不正な値です。的な文言だとどうでしょうか？

2022-06-15 01:03 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
idの値が正しいフォーマット(数字)ではないということがわかるメッセージならOK

2022-06-15 23:12 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
パラメータ値には数値を入力してください。に変更いたしました。
ご確認お願いします。
[a25c65c](https://github.com/k-tkm/kintai/pull/4/commits/a25c65cad4fe663fcbd554541252f81094f0eeed)

2022-06-16 00:24 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
他のレビューと同じで入力って単語は微妙な気がする
パラメータ値ってクエリパラメータも想像させるから良くないかな

2022-06-16 00:35 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
そうでした。
なかなかしっくり来る文言が出ないすね...
user_idの値￥￥には数値を使用してください。ってのもなんか変すかね？

2022-06-16 00:40 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
英語だとInvalid URL Pathってレスポンスにしたりするみたいだからそんな感じでいいと思う
パスパラメータは数字を使用してください的な

2022-06-16 00:44 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
> パスパラメータは数字を使用してください
これええすね。
これで修正します。

2022-06-16 00:51 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
修正しました。
[ea3c1ed](https://github.com/k-tkm/kintai/pull/4/commits/ea3c1ed8ce5410d911f8a8199e7d8a4835700cc6)

2022-06-16 00:56 UTC, kbwo approved these changes
@monz111 ぼく的にはOKなので確認お願いします
![LGTM](https://image.lgtmoon.dev/154896)

2022-06-16 01:06 UTC, monz111 commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
このメッセージをフロントに表示するならパスパラメータって書かれてもユーザは分からないと思う
不正なリクエストですとかのほうが良い気がする

2022-06-16 01:51 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
そもそもAPIのレスポンスをそのままフロントに表示すること自体がぼくは好きじゃないですが、そのままフロントに表示するならそうですね...

2022-06-16 01:53 UTC, monz111 commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
>そもそもAPIのレスポンスをそのままフロントに表示すること自体がぼくは好きじゃないですが

めっちゃ工数増えるやんけ！
それなら英語とかコードで良いな

2022-06-16 02:05 UTC, kbwo commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
> それなら英語とかコードで良いな
英語で書いてどう表示するかはフロントで決められるんだからフロントでやって派ですw
工数はまぁそうですけど自分なら綺麗にしたい

2022-06-16 02:11 UTC, monz111 commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
>英語で書いてどう表示するかはフロントで決められるんだからフロントでやって派ですw

全フロントエンドエンジニアを敵に回した！

@k-tkm これ方針決めてください。方針によってこのままにするか決めます

2022-06-17 00:09 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
おお、見ない間に議論されてたんすね。
一応、僕も元々このメッセージはフロント側で表示する想定はあまりしていなかったので、かばさわさん寄りの考え方ですね。

2022-06-17 00:14 UTC, k-tkm commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
なので、方針的にはこのメッセージはそのまま使って、フロントでユーザーの方にもわかるように表示すれば良いかと思っとります。

2022-06-17 00:50 UTC, monz111 commented on backend/src/modules/users/Dto/FindeOneParams.ts
> +  @IsNumberString({}, { message: 'このユーザーは存在していません。' })
分かりました。それで良いと思います

2022-06-17 00:50 UTC, monz111 approved these changes
![LGTM](https://i.lgtm.fun/1zpu.png)

2022-06-17 01:03 UTC, merged