create departments api
k-tkm/kintai pull request #5
Opened 2022-06-02 02:14 UTC by k-tkm

2022-06-17 02:08 UTC, kbwo requested changes
このPRでの変更じゃないけど以下も確認してください
勤怠のアプリケーションだと思うけど、論理削除よりstate(enum)で表現したほうがいいと思う
ユーザーでいうと、退職者とか、休職者は非表示にしたいとか諸々を表現できるほうがいい
stateと、日付的なものが欲しけりゃそれ用のテーブル作って正規化したほうがnullも減るしね
そもそも部署とかに論理削除がある場合ってその部署はどういう状態なのか、ぼく的には分かりづらい
https://www.slideshare.net/t_wada/ronsakucasual
あと、結合したときのtypeormのwithdeleteメソッドの仕様が分かりづらいのもある(withDeletedの位置によって結果が変わる)
https://stackoverflow.com/questions/66117005/typeorm-left-joining-without-deletedat-is-null

2022-06-17 02:08 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +      );
conflict用のExceptionて用意されてないんでしたっけ？HttpConflictException的な
あと、部署名がすでに作成されているってぼくは若干日本語違和感感じますね
作成されているデータは部署名というよりは部署なので
この部署名はすでに使用されていますとか

2022-06-17 02:08 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    }
この辺めちゃくちゃ分かりづらい
何やってるのかコード読まなきゃいけないのしんどいのでとりあえず関数に切り分けてください

2022-06-17 02:08 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    );
別関数に切り分けたほうがいいと思います

2022-06-17 02:08 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    await this.validateDuplicateName(departmentData.name, departmentID);
バリデーションはcontrollerもしくはミドルウェアから呼ぶのが責務的には正しい気がする

2022-06-17 02:08 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    await this.validateDuplicateName(departmentData.name);
バリデーションはcontrollerもしくはミドルウェアから呼ぶのが責務的には正しい気がする

2022-06-17 02:08 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +            user: user,
一個一個saveしてくと重くなると思います

2022-06-17 02:08 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    });
別関数に切り分けたほうがいいです

2022-06-17 02:08 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    }
なにやってるのか分かりづらい
この実装知らない人がこの関数使おうとすると、usersって何？渡すと何してくれんの？って疑問に思う

2022-06-17 02:08 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    }));
関数に切り分けたほうがいいですね

2022-06-20 01:16 UTC, k-tkm commented
> このPRでの変更じゃないけど以下も確認してください
勤怠のアプリケーションだと思うけど、論理削除よりstate(enum)で表現したほうがいいと思う
ユーザーでいうと、退職者とか、休職者は非表示にしたいとか諸々を表現できるほうがいい

了解です。違うブランチで修正するようにします。

> そもそも部署とかに論理削除がある場合ってその部署はどういう状態なのか、ぼく的には分かりづらい

その部署が、いついらなくなっのかは残しておきたいケースとかないすかね？

2022-06-20 01:27 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +      );
修正しました。
[df2ce1e](https://github.com/k-tkm/kintai/pull/5/commits/df2ce1ef076a76b4bd9a7b5c231a1683d2f0bfed)

2022-06-20 01:44 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    }));
修正しました。
[5fa5313](https://github.com/k-tkm/kintai/pull/5/commits/5fa53131d6eb0089f50a183388f93ec754a4df58)

2022-06-20 01:48 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    );
修正しました。
[634e49e](https://github.com/k-tkm/kintai/pull/5/commits/634e49e870e96c4c15e30c84d08a7f68dd8380e0)

2022-06-20 01:59 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    await this.validateDuplicateName(departmentData.name, departmentID);
controllerr内で呼び出すように修正したんですがこれで問題ないですか？
[66e492e](https://github.com/k-tkm/kintai/pull/5/commits/66e492e7a7eff1719c5f82473040b2857ed3308a)

2022-06-20 01:59 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    await this.validateDuplicateName(departmentData.name);
controllerr内で呼び出すように修正したんですがこれで問題ないですか？
[66e492e](https://github.com/k-tkm/kintai/pull/5/commits/66e492e7a7eff1719c5f82473040b2857ed3308a)

2022-06-20 02:05 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    });
修正しました。
[bad1b3c](https://github.com/k-tkm/kintai/pull/5/commits/bad1b3ce9120911c00116698f9d4d36d2a60d915)

2022-06-20 02:17 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +            user: user,
この書いたら問題ないですか？
[f865103](https://github.com/k-tkm/kintai/pull/5/commits/f8651036b424dea872e8f15f4453f044868d8f3c)

2022-06-20 02:24 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    }
修正しました。
[2251d99](https://github.com/k-tkm/kintai/pull/5/commits/2251d99bba1aed0a00fdc32cf95353c33f82d4c1)

2022-06-20 02:45 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    }
修正しました。
[26bd27d](https://github.com/k-tkm/kintai/pull/5/commits/26bd27de0a5485f0926e5dba0646213e7d898ecf)
[61599e9](https://github.com/k-tkm/kintai/pull/5/commits/61599e90058eca868aa271173d2d7090d83f7b30)

2022-06-20 05:35 UTC, kbwo requested changes

2022-06-20 05:35 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +  ): Promise<boolean> {
booleanじゃなくていいんじゃない？

2022-06-20 05:44 UTC, kbwo requested changes

2022-06-20 05:44 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    newUsersBelonging,
コード見た感じnewUsersというよりはremoveするときの"例外"な気がする

2022-06-20 05:44 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    await this.validateDuplicateName(departmentData.name);
controllerから呼び出すのであってバリデーションのロジックをcontrollerに書く意味ではないです

2022-06-20 05:44 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    }
mapでできないですか？

2022-06-20 05:44 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    return createdBelonging;
あれ、saveしなくていいんですかこれ？
あと、updateなのにcreateする可能性もあるのが変なので、updateって名前をやめるかcreateは他のメソッドにするかしてください

2022-06-22 00:18 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +  ): Promise<boolean> {
checkっていう命名をしたならbooleanで返す方が自然な気がするんですが、取得したデータをそのまま返すようにした方がいいですかね？

2022-06-22 00:33 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    newUsersBelonging,
なるほど...
じゃあusersExceptionRemoveとかっすかね。

2022-06-22 00:43 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    await this.validateDuplicateName(departmentData.name);
controllerから呼び出すってcontroller→serviceとかじゃなくてservice→controllerの順で呼び出せってことですか？

2022-06-22 03:38 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    }
修正しました。
[3b90fef](https://github.com/k-tkm/kintai/pull/5/commits/3b90fef36931e8b2c3b2ac6db1902b5f2c9c4ea3)

2022-06-22 03:48 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    return createdBelonging;
> あれ、saveしなくていいんですかこれ？

一応updateUserDepartmentsの最後にsaveをしているから大丈夫だとは思います。

> updateなのにcreateする可能性もあるのが変なので、updateって名前をやめるかcreateは他のメソッドにするかしてください

微妙な気もするけど、generateかmakeとかは命名としてありですか？

2022-06-23 04:37 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    newUsersBelonging,
直訳してexceptionにするとエラーハンドリングの方のexceptionと間違われそうだからexcludeとか使ってください

2022-06-23 04:41 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +  ): Promise<boolean> {
そもそもcheckって何をするのかわからない命名として有名なんで命名も変えなきゃですね
あとここで指摘したのは命名と返り値の対比的な意味ではなく、せっかくDB接続までしてるんだから、存在してたら存在したオブジェクトまで返したほうが汎用的に使いやすいんじゃない？ってことです
Boolean返すものほしいならこれのラッパー関数書けばいい

2022-06-23 04:43 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    return createdBelonging;
んんーまぁギリ及第点て感じだけどまぁ許せるかな

2022-06-23 04:46 UTC, kbwo commented
> その部署が、いついらなくなっのかは残しておきたいケースとかないすかね？
これ返信忘れてました
その要件が必要なら、なくなる以外にも部署の名前が変わったりとか色々状態は変わる可能性があって、きっとそれを記録して残しておきたいんだよね、ならstateとhistoryで表現したほうがいいと思います

2022-06-27 00:35 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    newUsersBelonging,
修正しました。
[5d545a8](https://github.com/k-tkm/kintai/pull/5/commits/5d545a8326b1cd397eab4e4a075bad353f02db1e)

2022-06-27 00:51 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +  ): Promise<boolean> {
> あとここで指摘したのは命名と返り値の対比的な意味ではなく、せっかくDB接続までしてるんだから、存在してたら存在したオブジェクトまで返したほうが汎用的に使いやすいんじゃない？ってことです

なるほど。了解です。
修正しました。
[12eea46](https://github.com/k-tkm/kintai/pull/5/commits/12eea461e5b68b635d2e9832970c055b6bc65ab5)

2022-06-27 00:54 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +    return createdBelonging;
修正しました。
[7c0ea17](https://github.com/k-tkm/kintai/pull/5/commits/7c0ea177ea6b7d9cb80f9f651c3160b02cd7891c)

2022-06-27 01:06 UTC, k-tkm commented
> その要件が必要なら、なくなる以外にも部署の名前が変わったりとか色々状態は変わる可能性があって、きっとそれを記録して残しておきたいんだよね、ならstateとhistoryで表現したほうがいいと思います

historyってのはそれようにテーブルを作って、stateが変わるたびにそのテーブルに保存していく感じですかね？
違うブランチで修正するようにします。

2022-06-27 01:17 UTC, k-tkm commented
https://github.com/k-tkm/kintai/pull/5#discussion_r901270544
上のレビューは、下のコミットで修正できてますかね？
[d3f0c40](https://github.com/k-tkm/kintai/pull/5/commits/d3f0c402d41974b813f95bec6fa251ac34efd510)

2022-06-27 01:41 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +  ): Promise<boolean> {
nameが一致するものを探すのにduplicate(重複)を探すっていうのはちょっとオーバーな気がする
findByName的な名前にしたほうがいいと思います

2022-06-27 01:46 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +    await this.validateDuplicateName(departmentData.name);
```
controller→serviceとかじゃなくてservice→controllerの順で呼び出
```
これの意味がわかんないけどコードは直ってたのでとりあえずresolveします

2022-06-27 01:48 UTC, kbwo commented
> 上のレビューは、下のコミットで修正できてますかね？

レビューの返信コメントの意味がよくわからなかったけど、直し方はそれであってるのでOKです

2022-06-27 01:51 UTC, kbwo commented on backend/src/modules/departments/departments.service.ts
> +  }
やっぱりまだものすごく何をやってるか分かりづらいのが気になるなぁ

2022-06-27 01:59 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +  ): Promise<boolean> {
修正しました。
[5dbe7f8](https://github.com/k-tkm/kintai/pull/5/commits/5dbe7f8beb3440d5069b4867b81a4dd80473aca3)

2022-06-27 02:00 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +  }
了解です。リファクタリングしてみます。

2022-06-27 02:33 UTC, k-tkm commented on backend/src/modules/departments/departments.service.ts
> +  }
修正しました。
[7aa0def](https://github.com/k-tkm/kintai/pull/5/commits/7aa0def4483df13f25f11e4ed2264ef52a4d31f7)

2022-12-14 14:01 UTC, merged